// Code generated by Slice Machine. DO NOT EDIT.

import AllSkateBoards from "./AllSkateBoards/index.svelte";
import Boards from "./Boards/index.svelte";

export const components = {
  all_skate_boards: AllSkateBoards,
  boards: Boards,
};
